# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-alpine
WORKDIR /app
# Install Python dependencies manually to avoid corrupted requirements.txt
RUN pip install --no-cache-dir supabase mcp
# Copy application code
COPY server.py ./
# Expose the port
EXPOSE 8000
# Set environment variables
ENV PORT=8000
# Run the server
CMD ["python", "server.py"]